require:
  - 'test_prof/rubocop'

plugins:
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - .rubocop_airbnb.yml

inherit_gem:
  test-prof: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'public/*'
Layout/DotPosition:
  EnforcedStyle: 'leading'
Layout/LineLength:
  Max: 200
Rails/I18nLocaleTexts:
  Enabled: false
Rails/ActionOrder:
  ExpectedOrder: [index, show, new, create, edit, update, destroy]
Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: 'never'
Style/RedundantSelf:
  Enabled: false
