require:
  - rubocop-rspec
  - 'test_prof/rubocop'

inherit_from:
  - .rubocop_airbnb.yml

inherit_gem:
  test-prof: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'public/*'
Layout/DotPosition:
  EnforcedStyle: 'leading'
Layout/LineLength:
  Max: 200
Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never
Style/RedundantSelf:
  Enabled: false
